-- Dogru cok dilli isimler (RU/KK/TR)
UPDATE categories AS c
SET name_ru = v.name_ru
FROM (VALUES
  ('eclairs-large', 'Эклеры большие'),
  ('eclairs-mini', 'Эклеры мини'),
  ('packaged-desserts', 'Десерты в упаковке'),
  ('art-desserts', 'Арт-десерты'),
  ('tarts', 'Тарты'),
  ('american-cakes', 'Американские торты'),
  ('classic-round-cakes', 'Классические круглые торты'),
  ('pies', 'Пироги'),
  ('cookies', 'Печенье'),
  ('boreks', 'Бореки'),
  ('samsa', 'Самса'),
  ('frozen-boreks', 'Бореки полуфабрикаты'),
  ('semi-finished', 'Полуфабрикаты')
) AS v(slug, name_ru)
WHERE c.slug = v.slug;

UPDATE products AS p
SET name_ru = v.name_ru
FROM (VALUES
  ('eclair-large-pistachio', 'Эклер фисташковый'),
  ('eclair-large-hazelnut', 'Эклер фундучный'),
  ('eclair-large-vanilla', 'Эклер ванильный'),
  ('eclair-large-mastic', 'Эклер дамла сакызы'),
  ('eclair-large-strawberry', 'Эклер клубничный'),
  ('eclair-large-raspberry', 'Эклер малиновый'),
  ('eclair-large-cherry', 'Эклер вишневый'),
  ('eclair-large-pineapple', 'Эклер ананасовый'),
  ('eclair-mini-pistachio', 'Эклер мини фисташковый'),
  ('eclair-mini-hazelnut', 'Эклер мини фундучный'),
  ('eclair-mini-vanilla', 'Эклер мини ванильный'),
  ('eclair-mini-mastic', 'Эклер мини дамла сакызы'),
  ('eclair-mini-strawberry', 'Эклер мини клубничный'),
  ('eclair-mini-raspberry', 'Эклер мини малиновый'),
  ('eclair-mini-cherry', 'Эклер мини вишневый'),
  ('eclair-mini-pineapple', 'Эклер мини ананасовый'),
  ('pistachio-cookies', 'Фисташковые cookies'),
  ('almond-kavala', 'Миндальные кавала'),
  ('eskimo-dubai', 'Эскимо с дубайской начинкой'),
  ('eskimo-strawberry', 'Эскимо с клубничной начинкой'),
  ('eskimo-oreo', 'Эскимо с начинкой OREO'),
  ('eskimo-caramel', 'Эскимо с карамельной начинкой'),
  ('kartoshka-dubai', 'Картошка с дубайской начинкой'),
  ('kartoshka-strawberry', 'Картошка с клубничной начинкой'),
  ('kartoshka-oreo', 'Картошка с начинкой OREO'),
  ('kartoshka-caramel', 'Картошка с карамельной начинкой'),
  ('samsa-meat', 'Самса с мясом'),
  ('samsa-chicken', 'Самса с курицей'),
  ('borek-meat', 'Борек с мясом'),
  ('borek-chicken', 'Борек с курицей'),
  ('borek-potato', 'Борек с картошкой'),
  ('borek-brinza', 'Борек с брынзой'),
  ('borek-spinach', 'Борек со шпинатом'),
  ('borek-lentils', 'Борек с чечевицей'),
  ('pack-cherry-brownie', 'Вишневый брауни'),
  ('pack-pistachio-raspberry', 'Фисташково-малиновый'),
  ('pack-oreo', 'Oreo'),
  ('pack-tiramisu', 'Тирамису'),
  ('pack-strawberry-cake', 'Клубничный десерт-торт'),
  ('pack-crunch', 'Кранч'),
  ('pack-lotus', 'Лотус'),
  ('pack-meringue-cake', 'Меренговый торт'),
  ('art-pistachio', 'Арт-десерт ФИСТАШКА'),
  ('art-lemon', 'Арт-десерт ЛИМОН'),
  ('art-coffee', 'Арт-десерт КОФЕ'),
  ('art-mango', 'Арт-десерт МАНГО'),
  ('art-heart', 'Арт-десерт СЕРДЦЕ'),
  ('art-raspberry', 'Арт-десерт МАЛИНА'),
  ('art-blueberry', 'Арт-десерт ГОЛУБИКА'),
  ('art-hamburger', 'Hamburger'),
  ('tart-dark-chocolate', 'Тарт темный шоколад'),
  ('tart-berry-mix', 'Тарт ягодный микс'),
  ('tart-lemon', 'Тарт лимонный'),
  ('tart-pistachio', 'Тарт фисташковый'),
  ('semi-waffle', 'Вафли'),
  ('frozen-borek-meat', 'Борек с мясом'),
  ('frozen-borek-chicken', 'Борек с курицей'),
  ('frozen-borek-potato', 'Борек с картошкой'),
  ('frozen-borek-brinza', 'Борек с брынзой'),
  ('frozen-borek-spinach', 'Борек со шпинатом'),
  ('frozen-borek-lentils', 'Борек с чечевицей'),
  ('kucuk-borek', 'Маленький борек'),
  ('sarma-borek', 'Борек сarma'),
  ('american-tiramisu', 'Тирамису'),
  ('american-strawberry-cake', 'Клубничный десерт-торт'),
  ('american-lotus', 'Лотус'),
  ('american-cherry-brownie', 'Брауни-вишневый'),
  ('american-pistachio-raspberry', 'Фисташково-малиновый'),
  ('mango-coconut-mousse', 'Мусс манго-кокос'),
  ('ferrero-hazelnut-mousse', 'Мусс Ferrero с фундуком'),
  ('cake-snickers', 'Торт Snickers'),
  ('cake-medovik', 'Медовик'),
  ('cake-milk-girl', 'Торт «Молочная девочка»'),
  ('cake-whoopie-pie', 'Whoopie Pie'),
  ('cake-red-velvet', 'Red Velvet'),
  ('cake-chocolate', 'Шоколадный торт'),
  ('cake-pistachio-raspberry', 'Торт фисташка-малина'),
  ('pie-apple-walnut-cinnamon', 'Пирог яблоко-орех-корица'),
  ('pie-snickers', 'Пирог Snickers'),
  ('pie-quark', 'Творожный пирог'),
  ('pie-meat', 'Мясной пирог'),
  ('pie-chicken', 'Пирог с курицей'),
  ('pie-spinach-cheese', 'Пирог шпинат-сыр'),
  ('pie-cheese', 'Сырный пирог')
) AS v(slug, name_ru)
WHERE p.slug = v.slug;
