-- Turkce urun isimleri — Supabase SQL Editor'de bir kez calistirin
UPDATE products AS p
SET name_tr = v.name_tr
FROM (VALUES
  ('eclair-large-pistachio', 'Fıstıklı Ekler'),
  ('eclair-large-hazelnut', 'Fındıklı Ekler'),
  ('eclair-large-vanilla', 'Vanilyalı Ekler'),
  ('eclair-large-mastic', 'Damla Sakızlı Ekler'),
  ('eclair-large-strawberry', 'Çilekli Ekler'),
  ('eclair-large-raspberry', 'Ahududulu Ekler'),
  ('eclair-large-cherry', 'Vişneli Ekler'),
  ('eclair-large-pineapple', 'Ananaslı Ekler'),
  ('eclair-mini-pistachio', 'Mini Fıstıklı Ekler'),
  ('eclair-mini-hazelnut', 'Mini Fındıklı Ekler'),
  ('eclair-mini-vanilla', 'Mini Vanilyalı Ekler'),
  ('eclair-mini-mastic', 'Mini Damla Sakızlı Ekler'),
  ('eclair-mini-strawberry', 'Mini Çilekli Ekler'),
  ('eclair-mini-raspberry', 'Mini Ahududulu Ekler'),
  ('eclair-mini-cherry', 'Mini Vişneli Ekler'),
  ('eclair-mini-pineapple', 'Mini Ananaslı Ekler'),
  ('pistachio-cookies', 'Fıstıklı Kurabiye'),
  ('almond-kavala', 'Badem Kavala'),
  ('eskimo-dubai', 'Eskimo — Dubai Dolgulu'),
  ('eskimo-strawberry', 'Eskimo — Çilek Dolgulu'),
  ('eskimo-oreo', 'Eskimo — Oreo Dolgulu'),
  ('eskimo-caramel', 'Eskimo — Karamel Dolgulu'),
  ('kartoshka-dubai', 'Kartoshka — Dubai Dolgulu'),
  ('kartoshka-strawberry', 'Kartoshka — Çilek Dolgulu'),
  ('kartoshka-oreo', 'Kartoshka — Oreo Dolgulu'),
  ('kartoshka-caramel', 'Kartoshka — Karamel Dolgulu'),
  ('samsa-meat', 'Etli Samsa'),
  ('samsa-chicken', 'Tavuklu Samsa'),
  ('borek-meat', 'Etli Börek'),
  ('borek-chicken', 'Tavuklu Börek'),
  ('borek-potato', 'Patatesli Börek'),
  ('borek-brinza', 'Peynirli Börek'),
  ('borek-spinach', 'Ispanaklı Börek'),
  ('borek-lentils', 'Mercimekli Börek'),
  ('pack-cherry-brownie', 'Vişneli Brownie'),
  ('pack-pistachio-raspberry', 'Fıstıklı Ahududulu'),
  ('pack-oreo', 'Oreo'),
  ('pack-tiramisu', 'Tiramisu'),
  ('pack-strawberry-cake', 'Çilekli Deser Kek'),
  ('pack-crunch', 'Crunch'),
  ('pack-lotus', 'Lotus'),
  ('pack-meringue-cake', 'Merengli Kek'),
  ('art-pistachio', 'Sanat Tatlı — Fıstık'),
  ('art-lemon', 'Sanat Tatlı — Limon'),
  ('art-coffee', 'Sanat Tatlı — Kahve'),
  ('art-mango', 'Sanat Tatlı — Mango'),
  ('art-heart', 'Sanat Tatlı — Kalp'),
  ('art-raspberry', 'Sanat Tatlı — Ahududu'),
  ('art-blueberry', 'Sanat Tatlı — Yaban Mersini'),
  ('art-hamburger', 'Hamburger'),
  ('tart-dark-chocolate', 'Bitter Çikolatalı Tart'),
  ('tart-berry-mix', 'Meyveli Tart'),
  ('tart-lemon', 'Limon Tart'),
  ('tart-pistachio', 'Fıstıklı Tart'),
  ('semi-waffle', 'Waffle'),
  ('frozen-borek-meat', 'Yarı Mamul Etli Börek'),
  ('frozen-borek-chicken', 'Yarı Mamul Tavuklu Börek'),
  ('frozen-borek-potato', 'Yarı Mamul Patatesli Börek'),
  ('frozen-borek-brinza', 'Yarı Mamul Peynirli Börek'),
  ('frozen-borek-spinach', 'Yarı Mamul Ispanaklı Börek'),
  ('frozen-borek-lentils', 'Yarı Mamul Mercimekli Börek'),
  ('kucuk-borek', 'Küçük Börek'),
  ('sarma-borek', 'Sarma Börek'),
  ('american-tiramisu', 'Tiramisu'),
  ('american-strawberry-cake', 'Çilekli Deser Kek'),
  ('american-lotus', 'Lotus'),
  ('american-cherry-brownie', 'Vişneli Brownie'),
  ('american-pistachio-raspberry', 'Fıstıklı Ahududulu'),
  ('mango-coconut-mousse', 'Mango Hindistan Cevizi Mus'),
  ('ferrero-hazelnut-mousse', 'Ferrero Fındıklı Mus'),
  ('cake-snickers', 'Snickers Pasta'),
  ('cake-medovik', 'Medovik'),
  ('cake-milk-girl', 'Süt Kızı Pastası'),
  ('cake-whoopie-pie', 'Whoopie Pie'),
  ('cake-red-velvet', 'Red Velvet Pasta'),
  ('cake-chocolate', 'Çikolatalı Pasta'),
  ('cake-pistachio-raspberry', 'Fıstıklı Ahududulu Pasta'),
  ('pie-apple-walnut-cinnamon', 'Elma Ceviz Tarçınlı Turta'),
  ('pie-snickers', 'Snickers Turta'),
  ('pie-quark', 'Lor Peynirli Turta'),
  ('pie-meat', 'Etli Turta'),
  ('pie-chicken', 'Tavuklu Turta'),
  ('pie-spinach-cheese', 'Ispanak Peynirli Turta'),
  ('pie-cheese', 'Peynirli Turta')
) AS v(slug, name_tr)
WHERE p.slug = v.slug;
