-- FISTIK — ürün fiyatları (menu.ts ile senkron)
-- Supabase SQL Editor → bir kez çalıştırın

UPDATE products SET price = CASE slug
  WHEN 'eclair-large-pistachio' THEN 750
  WHEN 'eclair-large-hazelnut' THEN 750
  WHEN 'eclair-large-vanilla' THEN 750
  WHEN 'eclair-large-mastic' THEN 750
  WHEN 'eclair-large-strawberry' THEN 750
  WHEN 'eclair-large-raspberry' THEN 750
  WHEN 'eclair-large-cherry' THEN 750
  WHEN 'eclair-large-pineapple' THEN 750
  WHEN 'eclair-mini-pistachio' THEN 450
  WHEN 'eclair-mini-hazelnut' THEN 450
  WHEN 'eclair-mini-vanilla' THEN 450
  WHEN 'eclair-mini-mastic' THEN 450
  WHEN 'eclair-mini-strawberry' THEN 450
  WHEN 'eclair-mini-raspberry' THEN 450
  WHEN 'eclair-mini-cherry' THEN 450
  WHEN 'eclair-mini-pineapple' THEN 450
  WHEN 'pistachio-cookies' THEN 550
  WHEN 'almond-kavala' THEN 1850
  WHEN 'eskimo-dubai' THEN 1100
  WHEN 'eskimo-strawberry' THEN 1100
  WHEN 'eskimo-oreo' THEN 1100
  WHEN 'eskimo-caramel' THEN 1100
  WHEN 'kartoshka-dubai' THEN 550
  WHEN 'kartoshka-strawberry' THEN 550
  WHEN 'kartoshka-oreo' THEN 550
  WHEN 'kartoshka-caramel' THEN 550
  WHEN 'samsa-meat' THEN 350
  WHEN 'samsa-chicken' THEN 350
  WHEN 'borek-meat' THEN 350
  WHEN 'borek-chicken' THEN 360
  WHEN 'borek-potato' THEN 330
  WHEN 'borek-brinza' THEN 330
  WHEN 'borek-spinach' THEN 330
  WHEN 'borek-lentils' THEN 1500
  WHEN 'pack-cherry-brownie' THEN 1850
  WHEN 'pack-pistachio-raspberry' THEN 2250
  WHEN 'pack-oreo' THEN 1650
  WHEN 'pack-tiramisu' THEN 1750
  WHEN 'pack-strawberry-cake' THEN 1950
  WHEN 'pack-crunch' THEN 1550
  WHEN 'pack-lotus' THEN 2250
  WHEN 'pack-meringue-cake' THEN 1750
  WHEN 'art-pistachio' THEN 1850
  WHEN 'art-lemon' THEN 1850
  WHEN 'art-coffee' THEN 1450
  WHEN 'art-mango' THEN 1850
  WHEN 'art-heart' THEN 1450
  WHEN 'art-raspberry' THEN 1450
  WHEN 'art-blueberry' THEN 1450
  WHEN 'art-hamburger' THEN 1500
  WHEN 'tart-dark-chocolate' THEN 1250
  WHEN 'tart-berry-mix' THEN 1950
  WHEN 'tart-lemon' THEN 1250
  WHEN 'tart-pistachio' THEN 1250
  WHEN 'semi-waffle' THEN 1500
  WHEN 'frozen-borek-meat' THEN 1500
  WHEN 'frozen-borek-chicken' THEN 1500
  WHEN 'frozen-borek-potato' THEN 1500
  WHEN 'frozen-borek-brinza' THEN 1500
  WHEN 'frozen-borek-spinach' THEN 1500
  WHEN 'frozen-borek-lentils' THEN 1500
  WHEN 'kucuk-borek' THEN 1500
  WHEN 'sarma-borek' THEN 1500
  WHEN 'american-tiramisu' THEN 1750
  WHEN 'american-strawberry-cake' THEN 1950
  WHEN 'american-lotus' THEN 2250
  WHEN 'american-cherry-brownie' THEN 1850
  WHEN 'american-pistachio-raspberry' THEN 2250
  WHEN 'mango-coconut-mousse' THEN 1500
  WHEN 'ferrero-hazelnut-mousse' THEN 1500
  WHEN 'cake-snickers' THEN 4990
  WHEN 'cake-medovik' THEN 1500
  WHEN 'cake-milk-girl' THEN 1500
  WHEN 'cake-whoopie-pie' THEN 1500
  WHEN 'cake-red-velvet' THEN 1500
  WHEN 'cake-chocolate' THEN 1500
  WHEN 'cake-pistachio-raspberry' THEN 4990
  WHEN 'pie-apple-walnut-cinnamon' THEN 1500
  WHEN 'pie-snickers' THEN 1500
  WHEN 'pie-quark' THEN 1500
  WHEN 'pie-meat' THEN 1500
  WHEN 'pie-chicken' THEN 1500
  WHEN 'pie-spinach-cheese' THEN 1500
  WHEN 'pie-cheese' THEN 1500
  ELSE 1500
END;
