-- FISTIK Full Menu Seed (auto-generated)

DELETE FROM products;
DELETE FROM categories;

INSERT INTO categories (slug, name_en, name_ru, name_kk, name_tr, sort_order) VALUES
  ('eclairs-large', 'Large Eclairs', 'Эклеры большие', 'Үлкен эклерлер', 'Büyük Ekler', 1),
  ('eclairs-mini', 'Mini Eclairs', 'Эклеры мини', 'Мини эклерлер', 'Mini Ekler', 2),
  ('packaged-desserts', 'Packaged Desserts', 'Десерты в упаковке', 'Қапталған десерттер', 'Paketli Tatlılar', 3),
  ('art-desserts', 'Art Desserts', 'Арт-десерты', 'Арт-десерттер', 'Art Tatlılar', 4),
  ('tarts', 'Tarts', 'Тарты', 'Тарттар', 'Tartlar', 5),
  ('american-cakes', 'American Cakes', 'Американские торты', 'Америкалық торттар', 'Amerikan Pastalar', 6),
  ('classic-round-cakes', 'Classic Round Cakes', 'Классические круглые торты', 'Классикалық дөңгелек торттар', 'Klasik Yuvarlak Pastalar', 7),
  ('pies', 'Pies', 'Пироги', 'Пирогтар', 'Turtalar', 8),
  ('cookies', 'Cookies', 'Печенья', 'Печенье', 'Kurabiyeler', 9),
  ('boreks', 'Boreks', 'Бореки', 'Боректер', 'Börekler', 10),
  ('samsa', 'Samsa', 'Самса', 'Самса', 'Samsa', 11),
  ('frozen-boreks', 'Frozen Boreks', 'Бореки полуфабрикаты', 'Борек жартылай дайын', 'Yarı Mamul Börekler', 12),
  ('semi-finished', 'Semi-finished Products', 'Полуфабрикаты', 'Жартылай дайын өнімдер', 'Yarı Mamul Ürünler', 13)
ON CONFLICT (slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-large-pistachio',
  (SELECT id FROM categories WHERE slug = 'eclairs-large'),
  'Pistachio Eclair',
  'Эклер фисташковый',
  'Фисташка эклер',
  'Fıstıklı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/pistachio.png',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-large-hazelnut',
  (SELECT id FROM categories WHERE slug = 'eclairs-large'),
  'Hazelnut Eclair',
  'Эклер фундучный',
  'Жаңғақ эклер',
  'Fındıklı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/hazelnut.png',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-large-vanilla',
  (SELECT id FROM categories WHERE slug = 'eclairs-large'),
  'Vanilla Eclair',
  'Эклер ванильный',
  'Ваниль эклер',
  'Vanilyalı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/vanilla.png',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-large-mastic',
  (SELECT id FROM categories WHERE slug = 'eclairs-large'),
  'Mastic Eclair',
  'Эклер дамла сакызы',
  'Damla sakız эклер',
  'Damla Sakızlı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/mastic.png',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-large-strawberry',
  (SELECT id FROM categories WHERE slug = 'eclairs-large'),
  'Strawberry Eclair',
  'Эклер клубничный',
  'Құлпынай эклер',
  'Çilekli Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/strawberry.png',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-large-raspberry',
  (SELECT id FROM categories WHERE slug = 'eclairs-large'),
  'Raspberry Eclair',
  'Эклер малиновый',
  'Таңқурай эклер',
  'Ahududulu Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/raspberry.png',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-large-cherry',
  (SELECT id FROM categories WHERE slug = 'eclairs-large'),
  'Cherry Eclair',
  'Эклер вишневый',
  'Шие эклер',
  'Vişneli Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/cherry.png',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-large-pineapple',
  (SELECT id FROM categories WHERE slug = 'eclairs-large'),
  'Pineapple Eclair',
  'Эклер ананасовый',
  'Ананас эклер',
  'Ananaslı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  8
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-mini-pistachio',
  (SELECT id FROM categories WHERE slug = 'eclairs-mini'),
  'Mini Pistachio Eclair',
  'Эклер мини фисташковый',
  'Мини фисташка эклер',
  'Mini Fıstıklı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/pistachio.png',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-mini-hazelnut',
  (SELECT id FROM categories WHERE slug = 'eclairs-mini'),
  'Mini Hazelnut Eclair',
  'Эклер мини фундучный',
  'Мини жаңғақ эклер',
  'Mini Fındıklı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/hazelnut.png',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-mini-vanilla',
  (SELECT id FROM categories WHERE slug = 'eclairs-mini'),
  'Mini Vanilla Eclair',
  'Эклер мини ванильный',
  'Мини ваниль эклер',
  'Mini Vanilyalı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/vanilla.png',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-mini-mastic',
  (SELECT id FROM categories WHERE slug = 'eclairs-mini'),
  'Mini Mastic Eclair',
  'Эклер мини дамла сакызы',
  'Мини damla sakız эклер',
  'Mini Damla Sakızlı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/mastic.png',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-mini-strawberry',
  (SELECT id FROM categories WHERE slug = 'eclairs-mini'),
  'Mini Strawberry Eclair',
  'Эклер мини клубничный',
  'Мини құлпынай эклер',
  'Mini Çilekli Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/strawberry.png',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-mini-raspberry',
  (SELECT id FROM categories WHERE slug = 'eclairs-mini'),
  'Mini Raspberry Eclair',
  'Эклер мини малиновый',
  'Мини таңқурай эклер',
  'Mini Ahududulu Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/raspberry.png',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-mini-cherry',
  (SELECT id FROM categories WHERE slug = 'eclairs-mini'),
  'Mini Cherry Eclair',
  'Эклер мини вишневый',
  'Мини шие эклер',
  'Mini Vişneli Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/eclairs/cherry.png',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eclair-mini-pineapple',
  (SELECT id FROM categories WHERE slug = 'eclairs-mini'),
  'Mini Pineapple Eclair',
  'Эклер мини ананасовый',
  'Мини анanas эклер',
  'Mini Ananaslı Ekler',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  8
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pistachio-cookies',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Pistachio Cookies',
  'Фисташковые cookies',
  'Фисташка cookies',
  'Pistachio Cookies',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/cookies/pistachio-cookies.png',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'almond-kavala',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Almond Kavala',
  'Миндальные кавала',
  'Миндаль kavala',
  'Almond Kavala',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/cookies/almond-kavala.png',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eskimo-dubai',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Eskimo — Dubai Filling',
  'Эскимо с дубайской начинкой',
  'Эскимо — Dubai начинкасы',
  'Eskimo — Dubai Filling',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eskimo-strawberry',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Eskimo — Strawberry Filling',
  'Эскимо с клубничной начинкой',
  'Эскимо — Құлпынай начинкасы',
  'Eskimo — Strawberry Filling',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eskimo-oreo',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Eskimo — OREO Filling',
  'Эскимо с начинкой OREO',
  'Эскимо — OREO начинкасы',
  'Eskimo — OREO Filling',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'eskimo-caramel',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Eskimo — Caramel Filling',
  'Эскимо с карамельной начинкой',
  'Эскимо — карамель начинкасы',
  'Eskimo — Caramel Filling',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'kartoshka-dubai',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Kartoshka — Dubai Filling',
  'Картошка с дубайской начинкой',
  'Картошка — Dubai начинкасы',
  'Kartoshka — Dubai Filling',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'kartoshka-strawberry',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Kartoshka — Strawberry Filling',
  'Картошка с клубничной начинкой',
  'Картошка — құлпынай начинкасы',
  'Kartoshka — Strawberry Filling',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  8
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'kartoshka-oreo',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Kartoshka — OREO Filling',
  'Картошка с начинкой OREO',
  'Картошка — OREO начинкасы',
  'Kartoshka — OREO Filling',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  9
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'kartoshka-caramel',
  (SELECT id FROM categories WHERE slug = 'cookies'),
  'Kartoshka — Caramel Filling',
  'Картошка с карамельной начинкой',
  'Картошка — карамель начинкасы',
  'Kartoshka — Caramel Filling',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  10
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'samsa-meat',
  (SELECT id FROM categories WHERE slug = 'samsa'),
  'Samsa with Meat',
  'Самса с мясом',
  'Етті самса',
  'Etli Samsa',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'samsa-chicken',
  (SELECT id FROM categories WHERE slug = 'samsa'),
  'Samsa with Chicken',
  'Самса с курицей',
  'Тауықты самса',
  'Tavuklu Samsa',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'borek-meat',
  (SELECT id FROM categories WHERE slug = 'boreks'),
  'Borek with Meat',
  'Борек с мясом',
  'Етті борек',
  'Etli Börek',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'borek-chicken',
  (SELECT id FROM categories WHERE slug = 'boreks'),
  'Borek with Chicken',
  'Борек с курицей',
  'Тауықты борек',
  'Tavuklu Börek',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'borek-potato',
  (SELECT id FROM categories WHERE slug = 'boreks'),
  'Borek with Potato',
  'Борек с картошкой',
  'Картопты борек',
  'Patatesli Börek',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'borek-brinza',
  (SELECT id FROM categories WHERE slug = 'boreks'),
  'Borek with Brinza Cheese',
  'Борек с брынзой',
  'Ірімшікті борек',
  'Peynirli Börek',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'borek-spinach',
  (SELECT id FROM categories WHERE slug = 'boreks'),
  'Borek with Spinach',
  'Борек со шпинатом',
  'Спанатты борек',
  'Ispanaklı Börek',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'borek-lentils',
  (SELECT id FROM categories WHERE slug = 'boreks'),
  'Borek with Lentils',
  'Борек с чечевицей',
  'Буршақты борек',
  'Mercimekli Börek',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pack-cherry-brownie',
  (SELECT id FROM categories WHERE slug = 'packaged-desserts'),
  'Cherry Brownie',
  'Вишневый брауни',
  'Шие брауни',
  'Vişneli Brownie',
  'Rich chocolate brownie with deep cocoa and dark chocolate flavor, complemented by a juicy cherry layer. Dense, chewy, and truly chocolatey.',
  'Насыщенный шоколадный брауни с глубоким вкусом какао и тёмного шоколада, дополненный сочной вишнёвой прослойкой. Плотный, тягучий и по-настоящему шоколадный десерт.',
  'Какао мен қара шоколадтың терең дәмі бар, шие қабатымен толықтырылған бай шоколад брауни. Тығыз, созылмалы және шынымен шоколадты десерт.',
  'Yoğun kakao ve bitter çikolata aromalı, sulu vişne katmanlı zengin brownie. Yoğun, yapışkan ve gerçekten çikolatalı bir tatlı.',
  2500,
  '/products/cherry-brownie.png',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pack-pistachio-raspberry',
  (SELECT id FROM categories WHERE slug = 'packaged-desserts'),
  'Pistachio Raspberry',
  'Фисташково-малиновый',
  'Фисташка-малина',
  'Fıstıklı Ahududulu',
  'Delicate pistachio sponge, airy cream and soft raspberry layer. Juicy, aromatic and perfectly balanced taste.',
  'Нежный фисташковый бисквит, воздушный крем и мягкая малиновая прослойка. Сочный, ароматный и идеально сбалансированный вкус.',
  'Жұмсақ фисташка бисквиті, жеңіл крем және жұмсақ таңқурай қабаты. Шырынды, хош иісті және тамаша теңдестірілген дәм.',
  'Hafif fıstıklı kek, havadar krema ve yumuşak ahududu katmanı. Sulu, aromatik ve mükemmel dengelenmiş bir lezzet.',
  2500,
  '/products/pistachio-raspberry.png',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pack-oreo',
  (SELECT id FROM categories WHERE slug = 'packaged-desserts'),
  'Oreo',
  'Oreo',
  'Oreo',
  'Oreo',
  'Delicate dessert with beloved Oreo flavor: creamy texture, chocolate base and cookie pieces in every layer. Rich, harmonious and soft taste.',
  'Нежный десерт с любимым вкусом Oreo: сливочная текстура, шоколадная основа и кусочки печенья в каждом слое. Насыщенный, гармоничный и мягкий вкус.',
  'Oreo дәмі бар нәзік десерт: кремді текстура, шоколад негізі және әр қабатта печенье үзінділері. Бай, үйлесімді және жұмсақ дәм.',
  'Sevilen Oreo lezzetli zarif tatlı: kremamsı doku, çikolatalı taban ve her katmanda bisküvi parçaları. Zengin, uyumlu ve yumuşak bir tat.',
  2500,
  '/products/oreo-dessert.png',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pack-tiramisu',
  (SELECT id FROM categories WHERE slug = 'packaged-desserts'),
  'Tiramisu',
  'Тирамису',
  'Тiramisu',
  'Tiramisu',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pack-strawberry-cake',
  (SELECT id FROM categories WHERE slug = 'packaged-desserts'),
  'Strawberry Dessert Cake',
  'Клубничный десерт-торт',
  'Құлпынай десерт-торт',
  'Strawberry Dessert Cake',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pack-crunch',
  (SELECT id FROM categories WHERE slug = 'packaged-desserts'),
  'Crunch',
  'Кранч',
  'Crunch',
  'Crunch',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pack-lotus',
  (SELECT id FROM categories WHERE slug = 'packaged-desserts'),
  'Lotus',
  'Лотус',
  'Lotus',
  'Lotus',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pack-meringue-cake',
  (SELECT id FROM categories WHERE slug = 'packaged-desserts'),
  'Meringue Cake',
  'Меренговый торт',
  'Меренга торт',
  'Meringue Cake',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  8
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'art-pistachio',
  (SELECT id FROM categories WHERE slug = 'art-desserts'),
  'Art Dessert — Pistachio',
  'Арт-десерт ФИСТАШКА',
  'Арт-десерт ФИСТАШКА',
  'Art Dessert — Pistachio',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/art-desserts/pistachio.png',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'art-lemon',
  (SELECT id FROM categories WHERE slug = 'art-desserts'),
  'Art Dessert — Lemon',
  'Арт-десерт ЛИМОН',
  'Арт-десерт ЛИМОН',
  'Art Dessert — Lemon',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/art-desserts/lemon.png',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'art-coffee',
  (SELECT id FROM categories WHERE slug = 'art-desserts'),
  'Art Dessert — Coffee',
  'Арт-десерт КОФЕ',
  'Арт-десерт КОФЕ',
  'Art Dessert — Coffee',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/art-desserts/coffee.png',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'art-mango',
  (SELECT id FROM categories WHERE slug = 'art-desserts'),
  'Art Dessert — Mango',
  'Арт-десерт МАНГО',
  'Арт-десерт МАНГО',
  'Art Dessert — Mango',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/art-desserts/mango.png',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'art-heart',
  (SELECT id FROM categories WHERE slug = 'art-desserts'),
  'Art Dessert — Heart',
  'Арт-десерт СЕРДЦЕ',
  'Арт-десерт ЖҮРЕК',
  'Art Dessert — Heart',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/art-desserts/heart.png',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'art-raspberry',
  (SELECT id FROM categories WHERE slug = 'art-desserts'),
  'Art Dessert — Raspberry',
  'Арт-десерт МАЛИНА',
  'Арт-десерт МАЛИНА',
  'Art Dessert — Raspberry',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'art-blueberry',
  (SELECT id FROM categories WHERE slug = 'art-desserts'),
  'Art Dessert — Blueberry',
  'Арт-десерт ГОЛУБИКА',
  'Арт-десерт Қарақат',
  'Art Dessert — Blueberry',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'art-hamburger',
  (SELECT id FROM categories WHERE slug = 'art-desserts'),
  'Hamburger',
  'Hamburger',
  'Hamburger',
  'Hamburger',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  8
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'tart-dark-chocolate',
  (SELECT id FROM categories WHERE slug = 'tarts'),
  'Dark Chocolate Tart',
  'Тарт темный шоколад',
  'Қара шоколад тарт',
  'Dark Chocolate Tart',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/tarts/dark-chocolate.png',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'tart-berry-mix',
  (SELECT id FROM categories WHERE slug = 'tarts'),
  'Berry Mix Tart',
  'Тарт ягодный микс',
  'Жидек микс тарт',
  'Berry Mix Tart',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/tarts/berry-mix.png',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'tart-lemon',
  (SELECT id FROM categories WHERE slug = 'tarts'),
  'Lemon Tart',
  'Тарт лимонный',
  'Лимон тарт',
  'Lemon Tart',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/tarts/lemon.png',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'tart-pistachio',
  (SELECT id FROM categories WHERE slug = 'tarts'),
  'Pistachio Tart',
  'Тарт фисташковый',
  'Фисташка тарт',
  'Pistachio Tart',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'semi-waffle',
  (SELECT id FROM categories WHERE slug = 'semi-finished'),
  'Waffle',
  'Waffle',
  'Waffle',
  'Waffle',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'frozen-borek-meat',
  (SELECT id FROM categories WHERE slug = 'frozen-boreks'),
  'Frozen Borek with Meat',
  'Борек с мясом',
  'Етті борек',
  'Frozen Borek with Meat',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'frozen-borek-chicken',
  (SELECT id FROM categories WHERE slug = 'frozen-boreks'),
  'Frozen Borek with Chicken',
  'Борек с курицей',
  'Тауықты борек',
  'Frozen Borek with Chicken',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'frozen-borek-potato',
  (SELECT id FROM categories WHERE slug = 'frozen-boreks'),
  'Frozen Borek with Potato',
  'Борек с картошкой',
  'Картопты борек',
  'Frozen Borek with Potato',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'frozen-borek-brinza',
  (SELECT id FROM categories WHERE slug = 'frozen-boreks'),
  'Frozen Borek with Brinza',
  'Борек с брынзой',
  'Ірімшікті борек',
  'Frozen Borek with Brinza',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'frozen-borek-spinach',
  (SELECT id FROM categories WHERE slug = 'frozen-boreks'),
  'Frozen Borek with Spinach',
  'Борек со шпинатом',
  'Спанатты борек',
  'Frozen Borek with Spinach',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'frozen-borek-lentils',
  (SELECT id FROM categories WHERE slug = 'frozen-boreks'),
  'Frozen Borek with Lentils',
  'Борек с чечевицей',
  'Бұршақты борек',
  'Frozen Borek with Lentils',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'kucuk-borek',
  (SELECT id FROM categories WHERE slug = 'frozen-boreks'),
  'Küçük Borek',
  'Kucuk borek',
  'Küçük borek',
  'Küçük Börek',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'sarma-borek',
  (SELECT id FROM categories WHERE slug = 'frozen-boreks'),
  'Sarma Borek',
  'Sarma borek',
  'Sarma borek',
  'Sarma Börek',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  8
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'american-tiramisu',
  (SELECT id FROM categories WHERE slug = 'american-cakes'),
  'Tiramisu',
  'Тирамису',
  'Tiramisu',
  'Tiramisu',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'american-strawberry-cake',
  (SELECT id FROM categories WHERE slug = 'american-cakes'),
  'Strawberry Dessert Cake',
  'Клубничный десерт-торт',
  'Құлпынай десерт-торт',
  'Strawberry Dessert Cake',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'american-lotus',
  (SELECT id FROM categories WHERE slug = 'american-cakes'),
  'Lotus',
  'Лотус',
  'Lotus',
  'Lotus',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'american-cherry-brownie',
  (SELECT id FROM categories WHERE slug = 'american-cakes'),
  'Cherry Brownie',
  'Брауни-вишневый',
  'Шие брауни',
  'Cherry Brownie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'american-pistachio-raspberry',
  (SELECT id FROM categories WHERE slug = 'american-cakes'),
  'Pistachio Raspberry',
  'Фисташково-малиновый',
  'Фисташка-малина',
  'Pistachio Raspberry',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'mango-coconut-mousse',
  (SELECT id FROM categories WHERE slug = 'american-cakes'),
  'Mango & Coconut Mousse',
  'Mango & Hindistan Cevizi',
  'Mango & Hindistan Cevizi Mousse',
  'Mango & Hindistan Cevizi',
  'Coconut mousse with mango insert and mango jelly. Light, fresh and tropical.',
  'Кокосовый мусс с манговой начинкой и манговым желе. Лёгкий, свежий и тропический вкус.',
  'Кокос мousse, mango insert және mango jöle. Жеңіл, сергек, тропикалық дәм.',
  'Hindistan cevizi mousse, mango insert ve mango jöle ile hafif, ferah ve tropikal bir lezzet.',
  2500,
  '/products/american-cakes/mango-coconut.png',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'ferrero-hazelnut-mousse',
  (SELECT id FROM categories WHERE slug = 'american-cakes'),
  'Ferrero Hazelnut Chocolate',
  'Ferrero Fındıklı Çikolata',
  'Ferrero Findik Mousse',
  'Ferrero Fındıklı Çikolata',
  'Chocolate mousse with hazelnut praline and croquant layers. Real Ferrero taste.',
  'Шоколадный мусс с фундучным пралине и хрустящими слоями. Настоящий вкус Ferrero.',
  'Фундук praliné және krokan қабаттары бар шоколад mousse. Шынайы Ferrero дәмі.',
  'Çikolata mousse, fındık praliné ve krokan katmanlarıyla zenginleştirilmiş gerçek Ferrero lezzeti.',
  2500,
  '/products/american-cakes/ferrero-hazelnut.png',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'cake-snickers',
  (SELECT id FROM categories WHERE slug = 'classic-round-cakes'),
  'Snickers Cake',
  'Snickers',
  'Snickers',
  'Snickers Cake',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'cake-medovik',
  (SELECT id FROM categories WHERE slug = 'classic-round-cakes'),
  'Medovik',
  'Medovik',
  'Medovik',
  'Medovik',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'cake-milk-girl',
  (SELECT id FROM categories WHERE slug = 'classic-round-cakes'),
  'Milk Girl Cake',
  'Malocni Devuska',
  'Malocni Devuska',
  'Milk Girl Cake',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'cake-whoopie-pie',
  (SELECT id FROM categories WHERE slug = 'classic-round-cakes'),
  'Whoopie Pie',
  'Vupi Pay',
  'Vupi Pay',
  'Whoopie Pie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'cake-red-velvet',
  (SELECT id FROM categories WHERE slug = 'classic-round-cakes'),
  'Red Velvet',
  'Krasni Barhat',
  'Krasni Barhat',
  'Red Velvet',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'cake-chocolate',
  (SELECT id FROM categories WHERE slug = 'classic-round-cakes'),
  'Chocolate Cake',
  'Cikolatali',
  'Cikolatali',
  'Chocolate Cake',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'cake-pistachio-raspberry',
  (SELECT id FROM categories WHERE slug = 'classic-round-cakes'),
  'Pistachio Raspberry Cake',
  'Fistik Malina',
  'Fistik Malina',
  'Pistachio Raspberry Cake',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pie-apple-walnut-cinnamon',
  (SELECT id FROM categories WHERE slug = 'pies'),
  'Apple Walnut Cinnamon Pie',
  'Elma ceviz tarcin',
  'Elma ceviz tarcin',
  'Apple Walnut Cinnamon Pie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  1
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pie-snickers',
  (SELECT id FROM categories WHERE slug = 'pies'),
  'Snickers Pie',
  'Snikerrs Pirog',
  'Snikerrs Pirog',
  'Snickers Pie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  2
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pie-quark',
  (SELECT id FROM categories WHERE slug = 'pies'),
  'Quark Pie',
  'Tvarok Pirog',
  'Tvarok Pirog',
  'Quark Pie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/pies/quark.png',
  3
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pie-meat',
  (SELECT id FROM categories WHERE slug = 'pies'),
  'Meat Pie',
  'Etli Pirog',
  'Etli Pirog',
  'Meat Pie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/pies/meat.png',
  4
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pie-chicken',
  (SELECT id FROM categories WHERE slug = 'pies'),
  'Chicken Pie',
  'Tavuklu Pirog',
  'Tavuklu Pirog',
  'Chicken Pie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/pies/chicken.png',
  5
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pie-spinach-cheese',
  (SELECT id FROM categories WHERE slug = 'pies'),
  'Spinach Cheese Pie',
  'Ispanak Peynirli Pirog',
  'Ispanak Peynirli Pirog',
  'Spinach Cheese Pie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/products/pies/spinach-cheese.png',
  6
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (slug, category_id, name_en, name_ru, name_kk, name_tr, description_en, description_ru, description_kk, description_tr, price, image_url, sort_order) VALUES (
  'pie-cheese',
  (SELECT id FROM categories WHERE slug = 'pies'),
  'Cheese Pie',
  'Peynirli Pirog',
  'Peynirli Pirog',
  'Cheese Pie',
  'Handcrafted fresh at Fistik bakery, Kaskelen.',
  'Свеже приготовлено в пекарне Fistik, Каскелен.',
  'Каскелендегі Fistik пекарнясында жаңа дайындалған.',
  'Kaskelen''deki Fistik fırınında taze hazırlanır.',
  2500,
  '/product-placeholder.jpg',
  7
) ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  name_tr = EXCLUDED.name_tr,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_kk = EXCLUDED.description_kk,
  description_tr = EXCLUDED.description_tr,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order;

